### ISSUE TITLE
Use of Trypanosoma gbff

### ISSUE THREAD

**Issue by alexranieri** [SystemsBioinformatics/cbmpy-metadraft#5]
Hi!

I'm trying to build a template model using Trypanosoma cruzi. However, I'm gettin an error:   
NITDB: connecting geneDB
INITDB: connecting notesDB
[('iIS312', 'iIS312.gbff', 'iIS312.xml')]
/media/alexranieri/Data/Trypanosoma/metadraft/Tbrucei/reference_model
/media/alexranieri/Data/Trypanosoma/metadraft/Tbrucei/reference_model
Processing: iIS312 iIS312.gbff iIS312.xml
INITDB: connecting geneDB
INFO: addGeneInformationToDB committed 0 new records
FBC version: 2
M.getNumReactions: 519
M.getNumSpecies: 606
FBC.getNumObjectives: 1
FBC.getNumParameters: 3
FBC.getNumGeneProducts: 312
Zero dimension compartment detected: c
Zero dimension compartment detected: e
Zero dimension compartment detected: x
Zero dimension compartment detected: m
Zero dimension compartment detected: n
Zero dimension compartment detected: r
FluxBounds process1: 0.01
INFO: Active objective: obj
Adding objective: obj
FluxBounds process2: 0.01

SBML3 load time: 0.57

CheckModelLocusTags is processing: /media/alexranieri/Data/Trypanosoma/metadraft/Tbrucei/reference_model/iIS312.gbff
INFO: Multiple sequences encountered in file: /media/alexranieri/Data/Trypanosoma/metadraft/Tbrucei/reference_model/iIS312.gbff
Traceback (most recent call last):
  File "/home/alexranieri/metadraft/cbmpy-metadraft/libpython/qtmetadraft.py", line 1615, in bp_createSeqPlusProcess
    compress_output=self.CREATE_TEMPLATE_ZIP)
  File "/home/alexranieri/metadraft/cbmpy-metadraft/libpython/biotools.py", line 946, in createSeqplusModel
    ) = checkModelLocusTags(fmod, fgb)
  File "/home/alexranieri/metadraft/cbmpy-metadraft/libpython/biotools.py", line 215, in checkModelLocusTags
    'isDescribedBy', 'PubMed', r_.pubmed_id
  File "/home/alexranieri/anaconda3/envs/metadraft3/lib/python3.7/site-packages/cbmpy/CBModel.py", line 771, in addMIRIAMannotation
    self.miriam.addMIRIAMannotation(qual, entity, mid)
  File "/home/alexranieri/anaconda3/envs/metadraft3/lib/python3.7/site-packages/cbmpy/CBDataStruct.py", line 380, in addMIRIAMannotation
    if self.checkId(E, mid):
  File "/home/alexranieri/anaconda3/envs/metadraft3/lib/python3.7/site-packages/cbmpy/CBDataStruct.py", line 333, in checkId
    if self.checkEntityPattern(entity):
  File "/home/alexranieri/anaconda3/envs/metadraft3/lib/python3.7/site-packages/cbmpy/CBDataStruct.py", line 316, in checkEntityPattern
    if type(self.MIRIAM[entity]['pattern']) == re._pattern_type:
AttributeError: module 're' has no attribute '_pattern_type'
Aborted (core dumped)

The model I'm using is: http://bigg.ucsd.edu/models/iIS312
And its genbank: https://sra-download.ncbi.nlm.nih.gov/traces/wgs03/wgs_aux/AY/LP/AYLP01/AYLP01.1.gbff.gz 

Is it a problem in the model, genbank or both?

**Comment by bgoli** [comment]
Hi thanks for reporting the problem and sorry that you have run into this now. 

This is a Python 3.7 issue with CBMPy (that will be fixed in the next release). For now the the easiest way is to create a Python 3.6 environment and run Metadraft. Alternatively you can install a development version of CBMPy which I can wrap make for you.

HTH

**Comment by alexranieri** [comment]
Thanks! It worked!
Need to change python version in environment.yml file.
